name: Run tests and publish the report
on: [push]

permissions: write-all

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Run tests
        run: |
          dotnet build --configuration Debug
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
          dotnet test --settings e2e.runsettings --logger "trx;LogFileName=allure-report.trx" --results-directory "allure-results"

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        if: always()
        run: |
          npm install -g allure-commandline
          if (Test-Path 'gh-pages\history') {
            Copy-Item -Path 'gh-pages\history\*' -Destination 'allure-results\history' -Recurse -Force
          }
          allure generate allure-results --clean -o allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history