name: Run tests and publish the report
on: [push]

permissions: write-all

jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Allure CLI
        run: npm install -g allure-commandline

      - name: Run tests
        run: |
          dotnet build --configuration Debug
          pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
          dotnet test --settings e2e.runsettings --logger "trx;LogFileName=allure-report.trx" --results-directory "allure-results"

      - name: List allure-results directory (debug)
        if: always()
        run: |
          Get-ChildItem -Path allure-results -Recurse | ForEach-Object { Write-Host $_.FullName }

      - name: Load test report history
        uses: actions/checkout@v4
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy Allure history for trend
        if: always()
        run: |
          if (Test-Path 'gh-pages\history') {
            New-Item -ItemType Directory -Path 'allure-results\history' -Force | Out-Null
            Copy-Item -Path 'gh-pages\history\*' -Destination 'allure-results\history' -Recurse -Force
          }

      - name: Build test report
        if: always()
        run: |
          allure generate allure-results --clean -o allure-history

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history